modLoader = "javafml"
loaderVersion = "[45,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "aether_enhanced_extinguishing"
version = "${file.jarVersion}"
displayName = "Enhanced Extinguishing"
credits = "The Aether Team"
authors = "bconlon"
description = '''Improves the consistency of fire being disallowed in the Aether by adding new extinguished variants of blocks.'''

[[dependencies.aether_enhanced_extinguishing]]
modId = "forge"
mandatory = true
versionRange = "[45.1.0,]"
ordering = "NONE"
side = "BOTH"
[[dependencies.aether_enhanced_extinguishing]]
modId = "aether"
mandatory = true
versionRange = "[1.19.4-1.0.0-beta.5-forge,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aether_enhanced_extinguishing]]
modId = "curios"
mandatory = true
versionRange = "[1.19.4-5.1.3.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aether_enhanced_extinguishing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4]"
ordering = "NONE"
side = "BOTH"